version: '3'
services:
  devops-app:
    build: .
    container_name: "devops-app"
    depends_on:
      - mongodb
    ports:
     - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/DevOpsApp 
  mongodb:
    image: mongo:4.0
    ports:
     - "27017:27017"
    volumes:
    - ./mongo-data:/data/db
