apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-app
    tier: backend
    track: stable
  name: devops-app
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: devops-app
    tier: backend
    track: stable
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  selector:
    matchLabels:
      app: devops-app
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: devops-app
        tier: backend
        track: stable
    spec:
      containers:
        - name: devops-app
          image: mosersts/devopsapp:k8s
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name:  MONGODB_URI
              value: "mongodb://mongodb:27017/DevOpsApp"   
            - name: GISTS_CRON
              value: "0 */3 * * *"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 90
            periodSeconds: 30